cd entrainement/build;
make; 
./main;
cd ../scripts;
#python3 DecisionTree.py;
#python3 SVM.py;
cd ..;
cp model/*.csv ../predict/model/;
cp model/*.cpp ../predict/src;
cp model/*.h ../predict/src;
cd ../predict/build;
make;
./main;