cd entrainement;
mkdir build;
mkdir model;
cd build;
cmake ..;
make; 
./main;
cd ../scripts;
python3 DecisionTree.py;
python3 SVM.py;
cd ..;
mkdir ../predict/model;
cp model/*.csv ../predict/model/;
cp model/*.cpp ../predict/src;
cp model/*.h ../predict/src;
cd ../predict;
mkdir build;
cd build;
cmake ..;
make;
./main;